### ISSUE TITLE
Create GUI tab "roll your own"

### ISSUE THREAD

**Issue by bmhm** [alttpj/MemeforceHunt#28]
The actual implementation.

Things which need to be included:

 - [x] 16x16px sprite editor
 - [ ] previews (just the icon and link standing in front of such a chest)
 - [ ] save/load to/from yaml and zspr
 - [x] transparent bg (small boxes white/gray)
 - [ ] maybe add a background layer of arbitrary PNGs/JPGs, so users have it easier to draw?
 - [x] palette swapping (transform existing coloured pixels to another of the three palettes)
 - [ ] swapping colours
 - [ ] make sure progress is not lost when app exists
 - [x] make sure progress is not lost when switching tabs
 - [ ] load pre-rolled sprites

**Comment by miketrethewey** [comment]
Swapping colors is less-likely if you mean to edit the global palette and thus everything else in the game that shares that palette.
Now, a way to edit the indices of each color so that you can change which color in the palette is being used, that could be cool.
Example: There's a red (`#ff0000`) in the loaded sheet from a `.png`, it's defined as index `1`, we're using the Red Global Palette, and we want to change everything that's in our index `1` to the index of wherever the Global Red is at (I don't know off the top of my head).

**Comment by bmhm** [comment]
Hi Mike,

the idea is another: Imagine you want to start drawing your sprite and then somehow need to use another palette because you need to use another colour. For this case it would be useful to create such a sprite swapping button (e.g. a dropwdown which palette to use).

See https://github.com/alttpj/MemeforceHunt/wiki/Palettes for available colours. Just updated it.

**Comment by bmhm** [comment]
Sketch for the editor

![preview grid editor memeforcehunt](https://user-images.githubusercontent.com/1413391/82078570-9e8bee00-96e1-11ea-8e79-43fc6e9d3b7b.png)

**Comment by bmhm** [comment]
Hey @miketrethewey,

this is what I meant with "swapping palettes". 

![paletteswap](https://user-images.githubusercontent.com/1413391/82459855-b59f5700-9ab8-11ea-9930-7111a909310c.gif)
